<?php

return array (
  0 => 
  array (
    'index' => 1001,
    'id' => 'about-images-right-section-mc',
    'elementId' => 'about-1',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-images-right-section-mc" data-export-id="about-images-right-section-mc" data-category="about" class="about-images-right-section-mc content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 content-left-sm" data-type="column"> <h5>WHAT WE DO</h5> <h2>We provide <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">creative solutions</span> for all your needs!</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">GET STARTED TODAY</a></div> <div class="col-sm-7 space-bottom-xs"><div class="image-group-side-3-img"> <img class="topimg shadow-large" src="[tag_child_theme_uri]/customizer/sections/images/cropped-paper-571937_1920.jpg"/> <img class="rightimg shadow-large" src="[tag_child_theme_uri]/customizer/sections/images/cropped-cropped-background-2726039-6x4.jpg"/> <div class="leftimg"> <img class="shadow-large" src="[tag_child_theme_uri]/customizer/sections/images/cropped-girl-2940655_1920.jpg"/></div> </div></div> </div></div> </div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/about-images-right-section-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/about-images-right-section-mc.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,flexAligns:[".image-group-side-3-img"]};',
    'replace' => 'about-images-right-section',
  ),
  1 => 
  array (
    'index' => 1002,
    'id' => 'blog-section-mc',
    'elementId' => 'latest-news-1',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'content' => '<div data-label="Latest-news" data-id="blog-section-mc" data-export-id="blog-section-mc" data-category="latest_news" class="blog-section-mc blog-section-standard content-section content-section-spacing"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h5>WE LOVE BLOGGING</h5> <h2>Latest from Our Blog</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="row"> <div data-type="row" data-dynamic-columns="handled" data-content-shortcode="mesmerize_latest_news posts=&quot;3&quot;">[mesmerize_latest_news]</div></div> <div class="row"><div class="text-center"> <a class="button color1" data-attr-shortcode="href:mesmerize_blog_link" href="[mesmerize_blog_link]">VIEW OUR BLOG</a></div> </div></div></div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/blog-section-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/blog-section-mc.png',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
    'replace' => 'blog-section',
  ),
  2 => 
  array (
    'index' => 1003,
    'id' => 'contact-1-mc',
    'elementId' => 'contact-1',
    'type' => 'section-available',
    'name' => 'Contact',
    'content' => '<div data-label="Contact" data-id="contact-1-mc" data-export-id="contact-1-mc" data-category="contact" class="contact-1-mc content-section content-section-spacing white-text" data-parallax-depth="20"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h5>CONNECT WITH US</h5> <h2>Contact us</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row text-center"> <div class="col-xs-12 col-sm-8 col-sm-offset-2 contact-form-wrapper inline-info"> <div class="card large-padding"> <div class="" data-content-shortcode="mesmerize_contact_form" data-editable="true">[mesmerize_contact_form]</div></div> </div></div> </div></div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/contact-1-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/contact-1-mc.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
    'replace' => 'contact-1',
  ),
  3 => 
  array (
    'index' => 1004,
    'id' => 'content-7-mc',
    'elementId' => 'content-1',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-7-mc" data-export-id="content-7-mc" data-category="content" class="content-7-mc content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm"><div class="col-sm-6 space-bottom-xs" data-type="column"> <h2>Web Design & Development</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">LEARN MORE</a></div> <div class="col-sm-6" data-type="column"> <img class="shadow-large" src="[tag_child_theme_uri]/customizer/sections/images/cropped-hero-3.jpg"></div> </div></div> </div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/content-7-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/content-7-mc.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\']}',
    'replace' => 'content-7',
  ),
  4 => 
  array (
    'index' => 1005,
    'id' => 'content-8-mc',
    'elementId' => 'content-2',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-8-mc" data-export-id="content-8-mc" data-category="content" class="content-8-mc content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm"><div class="col-sm-6 space-bottom-xs space-top-xs" data-type="column"> <img class="shadow-large" src="[tag_child_theme_uri]/customizer/sections/images/business-3560916_1920.jpg"></div> <div class="col-sm-6" data-type="column"><h2>App Design & Development</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <a class="button color1" href="#">LEARN MORE</a></div> </div></div> </div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/content-8-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/content-8-mc.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true}',
    'replace' => 'content-8',
  ),
  5 => 
  array (
    'index' => 1006,
    'id' => 'cta-blue-section-mc',
    'elementId' => 'cta-1',
    'type' => 'section-available',
    'name' => 'Cta',
    'content' => '<div data-label="Cta" data-id="cta-blue-section-mc" data-export-id="cta-blue-section-mc" data-category="cta" class="cta-blue-section-mc content-section content-section-spacing le_cocktail white-text"><div class="gridContainer"> <div class="row middle-xs"><div class="col-sm-8 space-bottom-xs" data-type="column"> <h2>Join us! <span class="font-300">It will only take a minute</span></h2> </div> <div class="col-sm-4 end-sm" data-type="column"> <a class="button color2" href="#">GET STARTED TODAY</a></div> </div></div> </div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/cta-blue-section-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/cta-blue-section-mc.png',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
    'replace' => 'cta-blue-section',
  ),
  6 => 
  array (
    'index' => 1007,
    'id' => 'features-16-card-bordered-mc',
    'elementId' => 'features-1',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-16-card-bordered-mc" data-export-id="features-16-card-bordered-mc" data-category="features" class="features-16-card-bordered-mc content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h5>WHAT WE OFFER</h5> <h2>We provide creative solutions!</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-4"> <div class="card no-padding bordered y-move"> <img class="face" src="[tag_child_theme_uri]/customizer/sections/images/agreement-2548139_1920.jpg"/> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class="col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> <div class="col-xs-12 col-sm-6 col-md-4"><div class="card no-padding bordered y-move"> <img class="face" src="[tag_child_theme_uri]/customizer/sections/images/pencils-452238_1920.jpg"/> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class="col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> <div class="col-xs-12 col-sm-6 col-md-4"><div class="card no-padding bordered y-move"> <img class="face" src="[tag_child_theme_uri]/customizer/sections/images/cropped-startup-849804_1920.jpg"/> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class="col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> </div></div> </div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/features-16-card-bordered-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/features-16-card-bordered-mc.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
    'replace' => 'features-16-card-bordered',
  ),
  7 => 
  array (
    'index' => 1008,
    'id' => 'features-ov-4-mc',
    'elementId' => 'features-2',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-ov-4-mc" data-export-id="features-ov-4-mc" data-category="features" class="features-ov-4-mc content-section content-section-spacing"><div class="gridContainer"> <div data-type="row" class="row spaced-cols text-center"><div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-clone large shadow-large-black round aligncenter reverse color1"></i> <div data-type="column"> <h5 class="font-400">RESPONSIVE DESIGN</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-cogs large shadow-large-black round aligncenter reverse color2"></i> <div data-type="column"><h5 class="font-400">SUPER FEATURES</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-magic large shadow-large-black round aligncenter reverse color4"></i> <div data-type="column"><h5 class="font-400">DRAG AND DROP</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/features-ov-4-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/features-ov-4-mc.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={}',
    'replace' => false,
  ),
  8 => 
  array (
    'index' => 1009,
    'id' => 'overlappable-4-mc',
    'elementId' => 'overlappable-1',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'content' => '<div data-label="Overlappable" data-id="overlappable-4-mc" data-export-id="overlappable-4-mc" data-category="overlappable" class="overlappable-4-mc content-section content-section-spacing" data-overlap="true"><div class="gridContainer"> <div data-type="row" class="row spaced-cols text-center"><div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-clone large shadow-large-black round aligncenter reverse color1"></i> <div data-type="column"> <h5 class="font-400">RESPONSIVE DESIGN</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-cogs large shadow-large-black round aligncenter reverse color2"></i> <div data-type="column"><h5 class="font-400">SUPER FEATURES</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-magic large shadow-large-black round aligncenter reverse color4"></i> <div data-type="column"><h5 class="font-400">DRAG AND DROP</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/overlappable-4-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/overlappable-4-mc.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro' => false,
    'export' => 'module.exports={allowSectionTitleOptions:false}',
    'replace' => 'overlappable-4',
  ),
  9 => 
  array (
    'index' => 1010,
    'id' => 'portfolio-5-mc',
    'elementId' => 'portfolio-1',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'content' => '<div data-label="Portfolio" data-id="portfolio-5-mc" data-export-id="portfolio-5-mc" data-category="portfolio" class="portfolio-5-mc content-section content-section-spacing section-title-col-white-text bg-color1"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h5>OUR WORK</h5> <h2>Portfolio</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua, ut aliquip ex ea commodo consequat.</p></div> </div> <div class="row space-bottom spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-4 text-center"> <div class="card no-padding bordered"> <div data-hover-fx="portfolio-6" class="contentswap-effect contentswap-overlay" style="float:none;margin:0;width:100%;"> <div class="initial-image" style="float:none;margin:0;"> <img data-size="500x333" src="[tag_child_theme_uri]/customizer/sections/images/cropped-pf-1.jpg"/></div> <div class="overlay bg-color6" style="display:block;transition:opacity 800ms ease 0s;-webkit-transition-timing-function:ease;-moz-transition-timing-function:ease;-o-transition-timing-function:ease;transition-timing-function:ease;"></div> <div class="swap-inner col-xs-12" style="display:block;transition:all 800ms ease 0s;background-color:rgba(0,0,0,0);margin-top:0;"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a class="button small color2" href="#">View case study</a></div> </div></div> </div> <div class="col-xs-12"> <div class="space-bottom space-top" data-type="column"> <h5 class="">Project Name</h5> <p class="small italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p></div> </div></div> </div> <div class="col-xs-12 col-sm-4 text-center"> <div class="card no-padding bordered"> <div data-hover-fx="portfolio-6" class="contentswap-effect contentswap-overlay" style="float:none;margin:0;width:100%;"> <div class="initial-image" style="float:none;margin:0;"> <img data-size="500x333" src="[tag_child_theme_uri]/customizer/sections/images/cropped-pf-3.jpg"/></div> <div class="overlay bg-color6" style="display:block;transition:opacity 800ms ease 0s;-webkit-transition-timing-function:ease;-moz-transition-timing-function:ease;-o-transition-timing-function:ease;transition-timing-function:ease;"></div> <div class="swap-inner col-xs-12" style="display:block;transition:all 800ms ease 0s;background-color:rgba(0,0,0,0);margin-top:0;"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a class="button small color2" href="#">View case study</a></div> </div></div> </div> <div class="col-xs-12"> <div class="space-bottom space-top" data-type="column"> <h5 class="">Project Name</h5> <p class="small italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p></div> </div></div> </div> <div class="col-xs-12 col-sm-4 text-center"> <div class="card no-padding bordered"> <div data-hover-fx="portfolio-6" class="contentswap-effect contentswap-overlay" style="float:none;margin:0;width:100%;"> <div class="initial-image" style="float:none;margin:0;"> <img data-size="500x333" src="[tag_child_theme_uri]/customizer/sections/images/cropped-pf-2.jpg"/></div> <div class="overlay bg-color6" style="display:block;transition:opacity 800ms ease 0s;-webkit-transition-timing-function:ease;-moz-transition-timing-function:ease;-o-transition-timing-function:ease;transition-timing-function:ease;"></div> <div class="swap-inner col-xs-12" style="display:block;transition:all 800ms ease 0s;background-color:rgba(0,0,0,0);margin-top:0;"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a class="button small color2" href="#">View case study</a></div> </div></div> </div> <div class="col-xs-12"> <div class="space-bottom space-top" data-type="column"> <h5 class="">Project Name</h5> <p class="small italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p></div> </div></div> </div></div> <div class="row"><div data-type="column" class="col-xs-12 text-center"> <a class="button color2 y-move" href="#">View Portfolio</a></div> </div></div> </div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/portfolio-5-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/portfolio-5-mc.png',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:"bg-",suffix:""}}]};',
    'replace' => 'portfolio-5',
  ),
  10 => 
  array (
    'index' => 1011,
    'id' => 'team-5-mc',
    'elementId' => 'team-1',
    'type' => 'section-available',
    'name' => 'Team',
    'content' => '<div data-label="Team" data-id="team-5-mc" data-export-id="team-5-mc" data-category="team" class="team-5-mc content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h5>OUR AWESOME TEAM</h5> <h2>Our Team</h2> <p class="lead">There are number of instructions to be followed at the time of refilling an inket cartridge. So whenever your printer ink runs dry you need to follow the below steps for inkjet cartridge refill.</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_child_theme_uri]/customizer/sections/images/team-1.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_child_theme_uri]/customizer/sections/images/team-7.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_child_theme_uri]/customizer/sections/images/team-3.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_child_theme_uri]/customizer/sections/images/team-4.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div></div> </div></div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/team-5-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/team-5-mc.png',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
    'replace' => 'team-5',
  ),
  11 => 
  array (
    'index' => 1012,
    'id' => 'testimonials-5-mc',
    'elementId' => 'testimonials-1',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'content' => '<div data-label="Testimonials" data-id="testimonials-5-mc" data-export-id="testimonials-5-mc" data-category="testimonials" class="testimonials-5-mc content-section content-section-spacing"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h5>OUR AWESOME CLIENTS</h5> <h2>Client Testimonials</h2> <p class="lead">Don\'t take our word for it - here\'s what our clients say:</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-sm-4"> <div class="card y-move bordered" data-type="column"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="text-center">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like “Hey, I think I\'ve been here before,</p> <img src="[tag_child_theme_uri]/customizer/sections/images/team-1.jpg" class="round icon"> <h6>John Doe</h6> <p class="small italic">Company name</p></div> </div> <div class="col-sm-4"> <div class="card y-move bordered" data-type="column"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="text-center">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like “Hey, I think I\'ve been here before,</p> <img src="[tag_child_theme_uri]/customizer/sections/images/team-3.jpg" class="round icon"> <h6>John Doe</h6> <p class="small italic">Company name</p></div> </div> <div class="col-sm-4"> <div class="card y-move bordered" data-type="column"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="text-center">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like “Hey, I think I\'ve been here before,</p> <img src="[tag_child_theme_uri]/customizer/sections/images/team-7.jpg" class="round icon"> <h6>John Doe</h6> <p class="small italic">Company name</p></div> </div></div> </div></div>',
    'thumb' => '[tag_child_theme_uri]/assets/customizer/previews/sections/testimonials-5-mc.png',
    'preview' => '[tag_child_theme_uri]/assets/customizer/previews/sections/testimonials-5-mc.png',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
    'replace' => 'testimonials-5',
  ),
);
